version: '3'
services: 
    db: 
        image: "mcr.microsoft.com/mssql/server:2019-latest"
        environment: 
            SA_PASSWORD: "s3curEp4$$$$1"
            ACCEPT_EULA: "Y"
    app:
        build: .
        ports:
            - "5001:80"
        depends_on:
            -   db