// <auto-generated />
using CF247TechTest.API.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CF247TechTest.API.Migrations
{
    [DbContext(typeof(CustomerContext))]
    partial class CustomerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CF247TechTest.API.Entities.CustomerEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(35);

                    b.Property<string>("Password")
                        .IsRequired();

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(35);

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new { Id = 1, Email = "aiyana.hue6@gmail.com", FirstName = "Shirley", Password = "ga5eiY8Ewee", Surname = "Murray" },
                        new { Id = 2, Email = "marquis_les@gmail.com", FirstName = "Matthew", Password = "quieCoodi6P", Surname = "McNeill" },
                        new { Id = 3, Email = "alvis2012@yahoo.com", FirstName = "Richard ", Password = "kahghei1aSu", Surname = "Headley" },
                        new { Id = 4, Email = "palma_oconn@hotmail.com", FirstName = "Elizabeth", Password = "ceZui6ok", Surname = "Marcus" },
                        new { Id = 5, Email = "eliseo2011@protonmail.com", FirstName = "David", Password = "shoop3Hoh", Surname = "Thomas" },
                        new { Id = 6, Email = "berry1979@gmail.com", FirstName = "Jerry", Password = "Imah5oav", Surname = "Conway" }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
